import { Box, Stack, Typography, styled } from '@mui/material'
import { StyledQABody, StyledQATitle } from 'pages/Testnet/TestnetV3'
import Collapse from 'components/Collapse/CollapseWhite'
import { useIsDarkMode } from 'state/user/hooks'

export const StyledCardWrapper = styled(Box)(({ theme }) => ({
  borderRadius: '16px',
  padding: '30px 28px',
  [theme.breakpoints.down('md')]: {
    padding: '16px'
  }
}))

const questionList = [
  [
    '1. What is Ladder?',
    `Ladder is a unique AMM (Automated Market Maker) that provides instant liquidity for NFTs (ERC-721, ERC-1155, ERC-3525), as well as ERC-20s. Unlike other NFT marketplaces which rely on order books to match buyers and sellers, Ladder uses liquidity pools, automated market makers and limit orders. By doing so, we aim to provide instant swaps for NFTs with low slippage and low fees! In addition, users who provide liquidity (NFT + ETH) will share trading fees generated by swaps from that respective liquidity pool.`
  ],

  [
    '2. Airdrop?',
    `YES! We are currently gearing up for the airdrop that is designed to reward our community and also ensure a healthy token distribution. From Testnet early adopters, to top traders, no one will be left behind.

  However, even if you just discovered Ladder now, you should know that it is not too late to earn Boxes!`
  ],

  [
    '3. What are Ladder Boxes?',
    `Ladder Boxes will contain Ladder tokens and some other rewards, but their roll chance will be influenced by your Luck! 

  Earn Ladder Boxes by completing eligible tasks!`
  ],
  [
    '4. What is the Luck meter?',
    `The Luck meter shows how likely it is for your boxes to contain better rewards! The more Luck you possess, the higher your chances of securing a top-tier reward. We have prepared separate tasks specifically designed to boost your Luck!

  NOTE: it does not cap at 100%!`
  ],
  [
    '5. What are Ladder SBTs?',
    'SBT stands for Soul-Bound Token and they represent tokens of appreciation awarded to winners of previous competitions and cross-IP events. Some SBT holders will be entitled to additional Ladder Boxes and some with a boost of Luck! 🍀'
  ],
  [
    '6. What is the Ladder token?',
    'Ladder aims to be a community-driven protocol, hence the Ladder token will serve 2 main purposes: governance and trading fee shares. By staking the Ladder token, users will get a cut of the trading fees generated by our NFT AMMs.'
  ]
]

const RowBetween = styled(Box)(({}) => ({
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center'
}))

export default function QuestionList() {
  const isDarkMode = useIsDarkMode()
  return (
    <Box width={'100%'} maxWidth={theme => theme.width.maxContent} margin="40px auto 0" padding={{ xs: 0, sm: 24 }}>
      <StyledCardWrapper id="qa">
        <Collapse
          defaultOpen
          title={
            <RowBetween>
              <Box display={'flex'}>
                <Typography fontSize={20} fontWeight={600} mb={20} variant="h5">
                  FAQ
                </Typography>
              </Box>
            </RowBetween>
          }
        >
          <Stack
            spacing={44}
            sx={{
              background: isDarkMode ? '#1A1C1E' : '#ffffff',
              borderRadius: 2,
              padding: '60px 24px'
            }}
          >
            {questionList.map(q => {
              return (
                <Box key={q[0]}>
                  <StyledQATitle>{q[0]}</StyledQATitle>
                  <StyledQABody>{q[1]}</StyledQABody>
                </Box>
              )
            })}
          </Stack>
        </Collapse>
      </StyledCardWrapper>
    </Box>
  )
}
